### ISSUE TITLE
Tensorflow newer versions 

### ISSUE THREAD

**Issue by Sabryr** [mohammad-adiban/probAI#1]
Hello and thank you for sharing code. 

I see that your code, although recently published is dependent on old Tensorflow version (https://github.com/tensorflow/tensorflow/releases/tag/v1.1.0, released 6 years a go).  As I am stuck with resent CUDA versions and NVIdia drivers, I can not install this on my test system. Could you recommend a way for me to test this and why it is tired to a old version of Tensorflow.  

Regards,
Sabry

**Comment by mohammad-adiban** [comment]
Hi Sabry,

Thank you for your comment.
Although I recently published the code in my repository, I implemented it 2 years ago. Here I should clarify some points:

  1.  In order to execute the code, please download the project and unzip the ProbAI_project.zip file and follow the instructions.
  2.  Normally, I use our department's servers, and these servers are different (e.g., in some of them, Python 2. is installed, in some of them, Python 3.6, and in some of them, Python 3.8). Since I work on big data and use many libraries, I am reluctant to use anaconda because anaconda is very (i) heavy and (ii), in many cases, the libraries installed on that might have conflicts. Therefore I prefer to install the required things (i.e, libraries) on servers myself. As the servers belong to our department and are shared between other students, I cannot install whatever I want, or I should consider the python version already installed on the server I work with.  Also, some libraries work only on Tensorflow 1. That's why I used TensorFlow 1.0.0 in this project.

To solve the problem, you can build a new virtual environment and install the requirements on that using anaconda and test the code.
I hope I could clarify that 🙂.

Please let me know if you have any questions.

Kind regards,
Mohammad

________________________________
From: Sabry Razick ***@***.***>
Sent: Friday, January 27, 2023 1:20 PM
To: mohammad-adiban/probAI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mohammad-adiban/probAI] Tensorflow newer versions (Issue #1)


Hello and thank you for sharing code.

I see that your code, although recently published is dependent on old Tensorflow version (https://github.com/tensorflow/tensorflow/releases/tag/v1.1.0, released 6 years a go). As I am stuck with resent CUDA versions and NVIdia drivers, I can not install this on my test system. Could you recommend a way for me to test this and why it is tired to a old version of Tensorflow.

Regards,
Sabry

**Comment by mohammad-adiban** [comment]
Also, in some cases, you can solve the problem by activating TensorFlow v1 when you have v2 installed. Please take a look at: https://www.tensorflow.org/guide/migrate/tf1_vs_tf2

**Comment by Sabryr** [comment]
Thank you for the clarification.
